### PR TITLE
Gym version compatibility issue; updated install setup and instructions 

### PR DESCRIPTION
**Pull request by bentotten**
Updated install to gym 0.20.0 to ensure environment compatibility (gym v0.21.0-v0.24.0 do not work with this environment - see https://github.com/openai/gym/issues/2840#issuecomment-1139312194 for further information). 

Clarified readme to include swig install instructions and created minor error-handling for working directory issue

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Is it clear what the change to v21 that caused this issue?

**Comment by peproctor** [comment]
thanks for catching and updating this Ben!

**Comment by peproctor** [comment]
@pseudo-rnd-thoughts @bentotten I tested on gym v0.24. There is now environment checks that are done in the `gym.make` call. 

Specifically [this line](https://github.com/openai/gym/blob/9147790e966dfbc491d44889eb141011ba5822c3/gym/wrappers/order_enforcing.py#L42 ) calls the `reset` method of the environment object which instantiates a SwigPyObject (these can't be serialized).

gym  versions < 0.21 likely do not have this specific environment checking but we will still get this failure if we call `env.reset()` and then try to pickle the environment.

**Comment by pseudo-rnd-thoughts** [comment]
Ok, that makes sense. This was a new feature in v0.24
For now, if users do `gym.make(..., disable_env_checker=True)`, that will stop the issue I believe. However, this feature maybe modified in the next release due to the number of issues that it is causing.

**Pull request merged**
